-- Clean-up
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS employee;
    

-- Table creation    
CREATE TABLE department (
    id                INTEGER    NOT NULL    PRIMARY KEY    AUTOINCREMENT
  , name              TEXT
);

CREATE TABLE employee (
    id                INTEGER    NOT NULL    PRIMARY KEY    AUTOINCREMENT
  , department_id     INTEGER    NOT NULL    
  , chief_id          INTEGER    NOT NULL    
  , name              TEXT
  , salary            INTEGER
  , FOREIGN KEY(department_id) REFERENCES department(id)
  , FOREIGN KEY(chief_id)      REFERENCES employee(id)
);


-- Sample data
BEGIN TRANSACTION;
    
INSERT INTO department(name) VALUES('Port Jonathan');
INSERT INTO department(name) VALUES('North Michelleshire');
INSERT INTO department(name) VALUES('East Cristianton');
INSERT INTO department(name) VALUES('Simmonston');
INSERT INTO department(name) VALUES('East Jessica');
INSERT INTO department(name) VALUES('Travisland');
INSERT INTO department(name) VALUES('Josephberg');
INSERT INTO department(name) VALUES('Lake Eric');
INSERT INTO department(name) VALUES('Port Amanda');
INSERT INTO department(name) VALUES('Lake Crystal');
INSERT INTO department(name) VALUES('East Maryshire');
INSERT INTO department(name) VALUES('Ginaton');
INSERT INTO department(name) VALUES('West Teresa');
INSERT INTO department(name) VALUES('East Stevenfurt');
INSERT INTO department(name) VALUES('South Annettefurt');
INSERT INTO department(name) VALUES('Sharpberg');
INSERT INTO department(name) VALUES('West Ann');
INSERT INTO department(name) VALUES('New Markborough');
INSERT INTO department(name) VALUES('Seanfurt');
INSERT INTO department(name) VALUES('Lake Tony');
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(11, 1, 'Carrie Wagner', 22379);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 2, 'Yvonne Berry', 94547);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(17, 2, 'Michael Alvarez', 116234);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 3, 'Nicholas Lopez', 44968);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(17, 4, 'David Skinner', 48553);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(2, 1, 'Eric Conner', 41498);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(19, 3, 'Amber Montgomery', 36408);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(8, 8, 'Steven Cooper', 46063);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(19, 9, 'Leslie Wilkerson', 87260);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(12, 5, 'Christopher Maldonado', 38563);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(12, 1, 'Kimberly Burnett', 53670);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 5, 'Connie Green', 24434);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(8, 1, 'Jorge Key', 101168);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 12, 'David Oliver', 91980);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(4, 4, 'Marcus Zimmerman', 110880);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(4, 16, 'Jim Jones', 33882);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(5, 1, 'Jesus Bishop', 99471);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 4, 'Jeffrey Morrow', 15064);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(5, 10, 'Daniel Summers', 23846);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(16, 7, 'Joshua Blake', 49538);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(6, 8, 'Jeanette Smith', 67374);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 13, 'Kristin Grant', 91001);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(4, 16, 'Hannah Armstrong', 93469);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 18, 'Jocelyn Anderson', 64992);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(17, 11, 'Mark Cobb', 55669);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 7, 'Cheryl King', 133554);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(20, 2, 'George Smith', 43802);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(15, 2, 'Kevin Parrish', 128989);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(6, 19, 'Dr. Timothy Bishop', 138177);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(13, 10, 'Margaret Davenport', 85181);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 8, 'Derek Jacobson', 114718);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(20, 13, 'Nathaniel Hancock', 57124);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(5, 14, 'Paul Douglas', 56193);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 18, 'Amanda Mills', 25197);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(7, 27, 'Eric Davis', 106987);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(6, 24, 'Brent Norris', 125360);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(14, 1, 'Sarah Sparks', 134388);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(13, 20, 'Pamela Stevenson', 75509);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(7, 28, 'Melissa Parker', 27594);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(16, 19, 'Bradley Phillips', 144030);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(7, 39, 'Steven Rodriguez', 78592);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(15, 15, 'Tammy Anderson', 46829);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 4, 'Gina Costa', 26755);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(7, 9, 'Jacob Moody', 134156);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(14, 39, 'Jonathan Mitchell', 98295);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(4, 12, 'Ashley Douglas', 108219);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(13, 43, 'Melissa Richardson', 105224);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(8, 15, 'John Powell', 90452);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 17, 'John Robbins', 52972);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(7, 44, 'Betty Robinson', 97827);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(18, 16, 'Mary Wiggins', 88872);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(17, 25, 'Stephanie Benitez', 120306);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(14, 26, 'Jessica Brown', 125387);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(5, 45, 'Taylor Hernandez', 120524);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(11, 15, 'Derrick Anderson', 30959);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(4, 3, 'Elizabeth Douglas', 118211);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 47, 'Brooke Jacobson', 41042);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 2, 'Natalie Chavez', 99675);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(19, 41, 'Brian Miranda', 92234);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(19, 48, 'Kimberly Ramsey', 51707);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(7, 19, 'Jennifer Torres', 71867);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 34, 'Vanessa Johnson', 13152);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 51, 'Timothy Hopkins', 133926);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(8, 45, 'Samantha Hendricks', 142951);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(5, 42, 'Shelby Fowler', 98897);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(10, 25, 'Wendy Obrien', 125062);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(6, 41, 'Amanda Berry', 107232);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(20, 28, 'Laura West', 80102);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 4, 'Omar Long', 92902);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 15, 'Michael Thornton', 125280);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(19, 35, 'Kathleen Foster', 140448);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(12, 41, 'Jennifer Johnson', 90442);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(18, 60, 'Kevin Bennett', 87665);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 50, 'Jennifer Guerra', 18778);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(10, 24, 'Jonathon Parker', 115728);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(19, 27, 'Eric Colon', 13215);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(18, 8, 'Madeline Kennedy', 121456);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(6, 64, 'Barbara Wilson', 128901);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(10, 18, 'Michael Hicks MD', 96648);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(18, 6, 'Joseph Campbell', 77434);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 76, 'Sylvia Rose', 127695);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(4, 27, 'Nicholas Molina', 147300);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(17, 25, 'Judith Lloyd', 17249);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(17, 56, 'Victoria Torres', 121686);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(7, 28, 'Shelby Brown', 63992);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(20, 21, 'Steven Carter', 125879);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(13, 1, 'Melvin Banks', 96952);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(13, 62, 'Julie Clark', 106334);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(14, 11, 'Dorothy Rivera', 79527);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(11, 9, 'Terry Wagner', 42931);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(14, 69, 'Amy Glover', 125845);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 2, 'Norman Collier PhD', 16428);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(12, 68, 'Kyle Moss', 19177);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(7, 55, 'Douglas Campbell', 18761);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(7, 48, 'Kathy Smith', 90979);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(19, 81, 'Steven Jones', 148701);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 97, 'Stephanie Whitaker', 60433);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(20, 11, 'Rebecca Newton', 80157);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(15, 17, 'Jason Goodman', 130564);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(12, 33, 'Kimberly Adams', 131091);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(10, 69, 'Jack Moore', 124947);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(20, 96, 'Katie Griffin DVM', 64422);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 95, 'Jason Sharp', 130595);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(17, 56, 'Amy Berry', 136648);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(18, 10, 'Steven Greer', 124464);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(16, 101, 'Jason Thompson', 102729);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(8, 68, 'Carolyn Lewis', 47534);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(5, 43, 'Jennifer Ruiz', 133294);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(16, 92, 'Alexander Pace', 143243);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(15, 26, 'Derrick Edwards', 50318);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 96, 'Patricia Lee', 43609);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(19, 55, 'Cheryl Flynn', 52142);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(7, 45, 'Nathan Romero', 92394);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 95, 'Patricia Silva', 141410);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 62, 'Brittany Simmons', 147800);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 22, 'Betty Johnson', 69273);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 105, 'Brandon Horton', 92369);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 101, 'Lynn Campbell', 31204);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(15, 36, 'John Hull', 110029);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(2, 102, 'Vanessa Thomas', 79309);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 36, 'Tyler Blackburn', 77628);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 117, 'Paul Mullen', 31847);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(5, 91, 'James Jones', 119792);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 33, 'Olivia Smith', 90172);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(14, 9, 'Douglas Ferguson', 77094);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(18, 88, 'Nathan Allen', 19438);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(2, 56, 'Kelli Salazar', 50707);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 83, 'John Hill', 121715);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(17, 76, 'Ariel King', 123502);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(7, 111, 'Heather Ramirez', 37018);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(5, 65, 'Jennifer Rocha', 137185);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 112, 'Natalie Robbins', 71622);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(13, 50, 'Travis White', 58267);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(17, 121, 'Jack Peterson', 27617);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(8, 62, 'Aaron Roberts', 112535);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(2, 10, 'Kevin Bonilla', 125910);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(13, 15, 'Joseph Ramos', 134465);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(2, 60, 'Miguel Flores', 36466);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(13, 109, 'Jesse Chen', 131731);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(14, 10, 'Michael Johnson', 136302);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(5, 29, 'Brooke Clark', 37151);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 49, 'Douglas Snow', 88381);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 25, 'Derrick Murphy', 76827);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(8, 48, 'Cody Hernandez', 137090);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(15, 82, 'Miss Jennifer Nixon', 119458);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 139, 'Jennifer Burns', 103055);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(10, 58, 'Carolyn Smith', 35115);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 66, 'Melissa Sullivan', 30113);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(16, 141, 'Amy Mcguire', 65044);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(19, 67, 'Jorge Clark', 106976);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(2, 119, 'Jeremy Gross', 50798);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(5, 49, 'Mary Hammond', 87080);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(8, 51, 'Amanda Brown', 70211);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(8, 123, 'Deborah Hanna', 112000);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(17, 152, 'Carrie Jones', 147529);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 131, 'James Buchanan', 35330);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 105, 'Elizabeth Jones', 118413);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 32, 'Bailey Abbott', 116576);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 54, 'Heather Miller', 68114);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 128, 'Brian Mckinney', 28297);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(8, 124, 'Jasmine Obrien', 100044);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(13, 120, 'Debra Williams', 66097);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(4, 90, 'Shelly Wood', 99603);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(4, 56, 'Thomas Adams', 53905);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(6, 19, 'Vincent Hood', 149938);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(6, 124, 'Michael Robbins', 145678);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(10, 75, 'Anna Franklin', 47234);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(11, 100, 'Erin Johnson', 62137);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(11, 152, 'George Harris', 91491);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(2, 28, 'Leroy Sanchez', 103684);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(6, 134, 'Linda Holmes', 35495);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(16, 72, 'Brittany Tyler', 58182);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(7, 3, 'Patrick Howard', 96191);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(13, 98, 'Caitlin Robinson', 70769);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 132, 'Luis Foster', 144774);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(8, 8, 'Jodi Serrano', 137226);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(16, 157, 'John Young', 33636);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(7, 169, 'Jose Perry', 39794);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(18, 81, 'Michael Robinson', 46169);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(13, 155, 'Tamara Peters', 30030);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(12, 177, 'Ronald Wood', 29210);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(13, 79, 'Veronica Curtis', 96464);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(4, 13, 'Jennifer Foster', 58112);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(20, 19, 'Ryan Gonzalez', 110807);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(10, 175, 'Christian Wright', 93089);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(5, 183, 'Emily Mccormick', 63222);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(1, 164, 'Jennifer Ritter', 77363);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(12, 50, 'Terry Scott MD', 46503);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(5, 32, 'Andrea Dominguez', 85949);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(5, 153, 'Sara Allen', 27290);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 52, 'Gail Brooks', 45375);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(18, 99, 'Andrew Jimenez', 129450);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 164, 'Diana Olsen', 23756);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(17, 52, 'Anna Lewis', 142934);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(3, 170, 'Anna Anderson', 81696);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(10, 7, 'Mrs. Megan King', 102654);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(9, 50, 'Kaitlyn Pace', 125372);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(19, 149, 'Autumn Matthews', 143411);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(4, 43, 'Michelle Elliott', 119990);
INSERT INTO employee(department_id, chief_id, name, salary)VALUES(2, 134, 'Preston Parker', 46310);

COMMIT TRANSACTION;
